apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jw-apps

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: congregations-api-config
    namespace: jw-apps
    env: config.env

secretGenerator:
  - name: congregations-api-secrets
    namespace: infra
    env: secrets.env
    type: Opaque