---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: congregations-api
  namespace: jw-apps
  labels:
    app: congregations-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: congregations-api
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
  minReplicas: 2
  maxReplicas: 4
