apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/component: congregations-api
    app.kubernetes.io/instance: congregations-api
    app.kubernetes.io/name: congregations-api
  name: congregations-api
  namespace: jw-apps
spec:
  ingressClassName: nginx
  rules:
    - host: congregations-api.ukrjw.org
      http:
        paths:
          - backend:
              service:
                name: congregations-api
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - congregations-api.ukrjw.org
      secretName: tls-secret
status:
  loadBalancer:
    ingress:
      - ip: 127.0.0.1