name: DB Migrations

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Commit, branch or tag to apply db migrations'
        required: true
        default: 'main'

jobs:
  migrate:
    environment: PROD
    name: Apply db migrations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.revision }}

      - name: Show current commit
        run: git log -1 --oneline

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl config use-context jw-prod

      - name: Run migrations scripts
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_NAME: ${{ vars.DB_NAME }}
          DB_SCHEMA: ${{ vars.DB_SCHEMA }}
        run: |
          make ENV=PROD db-migration/up